# Dynamic Programming: Set partition (of same sum)

In [30]:
import numpy as np

# Section 1: Data definition
principal_set = np.array([6, 3, 1, 4, 2])
total = np.sum(principal_set)
num_of_elements = len(principal_set)

could_be_solvable = True if total % 2 == 0 else False

if could_be_solvable:
    total = int(total / 2)
    matrix = np.zeros(shape=(total+1, num_of_elements+1))
    matrix[0] = [1] * (num_of_elements+1)

    # Section 2: Dynamic programming
    for row in range(1, total+1):
        for col in range(1, num_of_elements+1):
            matrix[row][col] = matrix[row][col-1]    # If the adjacent is 1, then is possible

            if row >= principal_set[col-1]:
                if matrix[row][col] == 1 or matrix[row - principal_set[col-1]][col-1] == 1:
                    matrix[row][col] = 1
                else:
                    matrix[row][col] = 0

    # Section 3: Answer search
    target_col = None
    target_row = total    # Last at first
    solution = list()

    for col in range(1, num_of_elements+1):
        if matrix[target_row][col] == 1:
            target_col = col
            break

    if target_col is None:
        print("The set cannot be split into 2 sets of the same sum")
    else:
        while target_row != 0:
            if matrix[target_row][target_col -1] == 1:
                target_col = target_col - 1
                continue

            solution.append(principal_set[target_col-1])
            target_row = target_row - principal_set[target_col-1]

    # Section 4: Answer report
    print(matrix)

    if len(solution) > 0:
        print('\nSet split:')
        print(np.array(solution))
        print(np.setdiff1d(principal_set, solution))
else:
    print("The set cannot be split into 2 sets of the same sum")

[[1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]

Set split:
[4 1 3]
[2 6]
